with bus_info_raw as (
    select * from {{ source('bus_info', 'bus_info') }}
),

parse_datetimes as (
    -- Raw string columns (event_time, event_time_utc, etc.) are retained via SELECT *
    -- to avoid SELECT * EXCLUDE, which Trino does not support. The parsed _prefixed
    -- columns are aliased back to their original names in the final stg_bus_info CTE.
    select
        *,
        {{ parse_datetime('event_time', '%y%m%d%H%M%S', 12) }} as _event_time,
        {{ parse_datetime('event_time_utc', '%y%m%d%H%M%S', 12) }} as _event_time_utc,
        {{ parse_datetime('trip_start_time', '%y%m%d%H%M%S', 12) }} as _trip_start_time,
        {{ parse_datetime('departure_time', '%y%m%d%H%M%S', 12) }} as _departure_time
    from bus_info_raw
),

service_dates as (
    select
        *,
        {{ date_add('_event_time', '-4', 'hour', 'day') }} as service_date
    from parse_datetimes
),

stg_bus_info as (
    select
        {{ dbt_utils.generate_surrogate_key(['file_name', 'batch_row_number']) }} as _row_id,
        product_version,
        route_id,
        stop_sequence,
        bus_id,
        dest_sign_code,
        dest_sign_type,
        _event_time as event_time,
        _event_time_utc as event_time_utc,
        stop_back_door_entry,
        stop_front_door_entry,
        stop_front_door_exit,
        stop_back_door_exit,
        odometer_distance,
        route_status,
        operator_id,
        run_id,
        {{ flex_cast("dwell_time", "integer", safe=True) }} as dwell_time,
        delta_time,
        stop_speed,
        dest_sign_route_text,
        latitude,
        longitude,
        heading,
        nav_state,
        event_type,
        bw_message,
        passenger_load,
        workid1,
        workid2,
        block_id,
        pattern_id,
        work_version,
        work_status,
        trip_id,
        trip_type,
        _departure_time as departure_time,
        timepoint_id,
        timepoint_type,
        timepoint_dwell,
        timepoint_status,
        wheel_chair,
        route_direction,
        demog_enabled,
        demog_01,
        demog_02,
        demog_03,
        demog_04,
        demog_05,
        demog_06,
        demog_07,
        demog_08,
        demog_09,
        demog_11,
        demog_12,
        demog_13,
        demog_14,
        demog_15,
        demog_16,
        demog_17,
        demog_18,
        demog_19,
        demog_21,
        demog_22,
        demog_23,
        demog_24,
        demog_25,
        demog_26,
        demog_27,
        demog_28,
        demog_29,
        apc_type,
        schedule_mode,
        bw_version,
        _trip_start_time as trip_start_time,
        stop_id,
        bicycle_event,
        kneel_event,
        tsp_event,
        geofence_id,
        {{ flex_cast('geofence_enter_time', 'timestamp') }} as geofence_enter_time,
        {{ flex_cast('geofence_exit_time', 'timestamp') }} as geofence_exit_time,
        ta_geo_id,
        geofence_type,
        text_msg,
        text_msg_category,
        cad_msg_id,
        ack_return_code,
        fare_zone,
        transfer_id,
        stop_rear_door_only_entry,
        stop_rear_door_only_exit,
        stop_center_door_only_entry,
        stop_center_door_only_exit,
        stop_aux2_door_entry,
        stop_aux2_door_exit,
        odometer_cumulative,
        file_name,
        batch_id,
        batch_row_number,
        update_date,
        filedate,
        service_date
    from service_dates
)

select * from stg_bus_info