{{ config(enabled=var('enable_realtime', false)) }}

with realtime_bus_info_raw as (
    select * from {{ source('near_realtime_bus_info', 'bus_avl_data_source') }}
),

parse_datetimes as (
    select
        *,
        {{ as_timestamp('lastrecrcvddts') }} as _lastrecrcvddts,
        {{ as_timestamp('llhfilterdts') }} as _llhfilterdts,
        {{ as_timestamp('onrtdts') }} as _onrtdts,
        {{ as_timestamp('offrtdts') }} as _offrtdts,
        {{ as_timestamp('tripstartdts') }} as _tripstartdts,
        {{ as_timestamp('pwrondts') }} as _pwrondts,
        {{ as_timestamp('pwroffdts') }} as _pwroffdts,
        {{ as_timestamp('nocomsdts') }} as _nocomsdts,
        {{ as_timestamp('comsdts') }} as _comsdts,
        {{ as_timestamp('depotoutdts') }} as _depotoutdts,
        {{ as_timestamp('depotindts') }} as _depotindts,
        {{ as_timestamp('logondts') }} as _logondts,
        {{ as_timestamp('logoffdts') }} as _logoffdts,
        {{ as_timestamp('logonservicedate') }} as _logonservicedate,
        {{ as_timestamp('logoninvddts') }} as _logoninvddts,
        {{ as_timestamp('mechanicalalarmdts') }} as _mechanicalalarmdts,
        {{ as_timestamp('adddts') }} as _adddts,
        {{ as_timestamp('upddts') }} as _upddts,
        {{ as_timestamp('locationupdatedts') }} as _locationupdatedts,
        {{ as_timestamp('timepointdts') }} as _timepointdts,
        {{ as_timestamp('blockstartdts') }} as _blockstartdts,
        {{ as_timestamp('routestartdts') }} as _routestartdts,
        {{ as_timestamp('idlesincedts') }} as _idlesincedts,
        {{ as_timestamp('comsstdts') }} as _comsstdts,
        {{ as_date('servicedate') }} as original_service_date
    from realtime_bus_info_raw
),

service_dates as (
    select
        *,
        {{ date_add('_upddts', -4, 'HOUR', 'DAY') }} as service_date
    from parse_datetimes
),

stg_realtime_bus_info as (
    select
        vehicleworkid,
        vehicleid,
        vehiclenumber,
        versionid,
        verscheduleid,
        verfirmware,
        runworkid,
        blockworkid,
        _lastrecrcvddts as lastrecrcvddts,
        calendarindex,
        _llhfilterdts as llhfilterdts,
        isllvalid,
        latitude,
        longitude,
        dirid,
        hdgdeg,
        scheddev,
        scheddevid,
        speed,
        _onrtdts as onrtdts,
        _offrtdts as offrtdts,
        routestatusid,
        vehiclestatusid,
        servicetypeid,
        original_service_date,
        {{ flex_cast(flex_cast('currenttripid', 'bigint'), 'varchar') }} as currenttripid,
        currentroutevarid,
        currenttimepointid,
        currentgeopathid,
        {{ flex_cast('currentstopid', 'varchar') }} as currentstopid,
        nextstopid,
        tripid,
        triptypeid,
        _tripstartdts as tripstartdts,
        lasttimepoint,
        nexttimepoint,
        isbusfull,
        apcon,
        apcoff,
        apccount,
        wheelchairon,
        wheelchairoff,
        wheelchaircount,
        _pwrondts as pwrondts,
        _pwroffdts as pwroffdts,
        pwrstatusid,
        _nocomsdts as nocomsdts,
        _comsdts as comsdts,
        comsstatusid,
        vehassigneddepotid,
        isindepot,
        _depotoutdts as depotoutdts,
        _depotindts as depotindts,
        depotidlastout,
        depotidlastin,
        employeeid,
        isoploggedon,
        _logondts as logondts,
        logontype,
        _logoffdts as logoffdts,
        logofftype,
        _logonservicedate as logonservicedate,
        logonspecialopt,
        islogonautomation,
        logoninvdatmpts,
        _logoninvddts as logoninvddts,
        logoninvdopid,
        logoninvdwid1,
        logoninvdwid2,
        logoninvdrc,
        workinvdrc,
        issystemlogoff,
        issysendwork,
        isworkonveh,
        worktypeid,
        mechanicalstatusid,
        _mechanicalalarmdts as mechanicalalarmdts,
        vehinstanceid,
        adduserid,
        _adddts as adddts,
        upduserid,
        _upddts as upddts,
        _locationupdatedts as locationupdatedts,
        _timepointdts as timepointdts,
        runid,
        logvehicleworkid,
        eastate,
        blockid,
        _blockstartdts as blockstartdts,
        _routestartdts as routestartdts,
        minscheddev,
        maxscheddev,
        wheelchairdeployment,
        nexttripid,
        _comsstdts as comsstdts,
        availabilitystatus,
        consistid,
        runblockid,
        detourroutevarid,
        detourversion,
        islayover,
        _idlesincedts as idlesincedts,
        worklogontypeid,
        paratransitrunid,
        busbridgeroutevarid,
        doorstatus,
        routeheadwaymins,
        routetargetheadwaymins,
        routeleadingvehiclenumber,
        routegroupheadwaymins,
        routegrouptargetheadwaymins,
        routegroupleadingvehiclenumber,
        isdynamic,
        avgspeed,
        driverblock,
        runworkstatusid,
        vehicledecorationid,
        tapatternid,
        isflexservice,
        tripdetailid,
        service_date
    from service_dates
)

select * from stg_realtime_bus_info