with source as (
    select *
    from {{ source('fare', 'fare_sale') }}
),

stg_fare_sale as (
    select
        rowid as _row_id,
        device_id,
        {{ flex_cast('transaction_id', 'varchar') }} as transaction_id,
        {{ flex_cast('transaction_dtm', 'timestamp') }} as transaction_dtm,
        {{ date_add(flex_cast('transaction_dtm', 'timestamp'), '-4', 'HOUR', 'DAY') }} as service_date,
        operator_id,
        media_type_id,
        sale_transaction_type,
        {{ flex_cast('quantity', 'double') }} as quantity,
        bonus_added,
        rides_added,
        deposit,
        sv_amount_used,
        cr_db_amount,
        region_id,
        data_format,
        rev_or_test,
        country,
        agency_id,
        transaction_status_cd,
        fare_instrument_id,
        service_type,
        inserted_dtm,
        updated_dtm,
        processed_flag,
        facid,
        autoload_event_id,
        sv_transaction,
        sv_remaining,
        rides_remaining,
        net_value,
        {{ flex_cast('bus_id', 'varchar') }} as bus_id,
        {{ flex_cast('run_id', 'varchar') }} as run_id,
        {{ flex_cast('route_id', 'varchar') }} as route_id,
        fare_table_id,
        receipt_issued,
        load_type_id,
        product_use_load_id,
        authority_id,
        cash_collected,
        action_cd,
        retrieval_ref_num,
        replacement_fee,
        merchant_id,
        merchant_type,
        administrative_fee,
        route_number,
        receipt_ticket_number,
        date_cutover_time,
        response_code,
        auth_id_response,
        pos_entry_mode,
        processing_code,
        terminal_id,
        alighting_stop,
        high_zone,
        low_zone,
        group_id,
        group_seq_no,
        home_garage,
        benefit_value,
        boarding_stop,
        local_logon_id,
        device_transaction_id,
        latitude,
        longitude,
        transit_mode_id,
        participant_inserted_dtm,
        participant_transit_day,
        participant_financial_day,
        eod_processed_flag,
        fa_processed_flag,
        alp_txn_flag,
        fare_level_id,
        run_route_record_identifier,
        lat_long_data,
        incorrect_transaction_dtm,
        inter_fare_queue_mesg_nbr,
        inter_fare_queue_batch_nbr,
        orig_transaction_status_cd,
        serial_nbr,
        employee_id,
        employee_identification,
        employee_serial_nbr
    from source
)

select * from stg_fare_sale