with source as (
    select *
    from {{ source('fare', 'fare_use') }}
),

stg_fare_use as (
    select
        rowid as _row_id,
        device_id,
        {{ flex_cast('transaction_id', 'varchar') }} as transaction_id,
        {{ flex_cast('transaction_dtm', 'timestamp') }} as transaction_dtm,
        {{ date_add(flex_cast('transaction_dtm', 'timestamp'), '-4', 'HOUR', 'DAY') }} as service_date,
        operator_id,
        use_transaction_type,
        media_type_id,
        country,
        region_id,
        {{ flex_cast('riders', 'double') }} as riders,
        service_type,
        inserted_dtm,
        updated_dtm,
        {{ flex_cast('run_id', 'varchar') }} as run_id,
        {{ flex_cast('bus_id', 'varchar') }} as bus_id,
        fare_table_id,
        manual_override,
        use_type,
        journey_start_dtm,
        sv_remaining,
        sv_transaction,
        sv_adjusted_txn,
        rides_remaining,
        days_valid,
        fare_instrument_id,
        agency_id,
        product_use_load_id,
        validity_period,
        transaction_status_cd,
        transfer_count,
        start_dtm,
        data_format,
        rev_or_test,
        {{ flex_cast(flex_cast('stop_point_id', 'bigint'), 'varchar') }} as stop_point_id,
        previous_stop_point_id,
        last_use_operator_id,
        {{ flex_cast('route_id', 'varchar') }} as route_id,
        facid,
        authority_id,
        home_garage,
        local_logon_id,
        route_number,
        device_transaction_id,
        latitude,
        longitude,
        transit_mode_id,
        participant_inserted_dtm,
        participant_transit_day,
        serial_nbr,
        employee_id,
        employee_identification,
        employee_serial_nbr
    from source
)

select * from stg_fare_use